config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :questions do
    resources :answers, shallow: true, only: %i[create update destroy] do
      patch :mark_as_best, on: :member
    end
  end

  root to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  default_scope { order(best: :desc, id: :asc) }

  belongs_to :question, inverse_of: :answers
  belongs_to :user, inverse_of: :answers

  has_many_attached :files

  validates :body, presence: true

  def mark_as_best!
    transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, inverse_of: :questions
  has_many :answers, dependent: :destroy

  has_many_attached :files

  validates :title, :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def author_of?(content)
    content.user_id == self.id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_author, except: %i[create mark_as_best]
  before_action :check_question_author, only: %i[mark_as_best]

  def create
    @answer = Answer.new(answer_params)
    @answer.question = question
    @answer.user = current_user
    @answer.save
  end

  def update
    answer.update(body: answer_params[:body])
    answer.files.attach(answer_params[:files])
    @question = answer.question
  end

  def mark_as_best
    answer.mark_as_best! unless answer.best?
    @best_answer = answer
  end

  def destroy
    answer.destroy
  end

  private

  def check_author
    render status: :forbidden unless current_user.author_of?(answer)
  end

  def check_question_author
    render status: :forbidden unless current_user.author_of?(answer.question)
  end

  def answer
    @answer ||= Answer.find(params[:id])
  end

  def question
    @question ||= params[:question_id].present? ? Question.find(params[:question_id]) : answer.question
  end

  helper_method :question

  def answer_params
    params.require(:answer).permit(:body, files: [])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :check_author, only: %i[mark_answer update destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answers = question.answers
  end

  def new; end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created'
    else
      render :new
    end
  end

  def update
    question.update(question_params.reject { |key, _val| key == :files })
    question.files.attach(question_params[:files])
  end

  def destroy
    question.destroy
  end

  private

  def check_author
    render status: :forbidden unless current_user.author_of?(question)
  end

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  helper_method :question

  def question_params
    params.require(:question).permit(:title, :body, files: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
  def add_answer_form(question, answer)
    render('answers/new', question: question, answer: answer) unless current_user.nil?
  end
end

app/views/answers/_answer.html.slim
.answer id="#{answer.id}" class=('best-answer' if answer.best?)
  .body= answer.body

  .attachments
    -if answer.files.attached?
      -answer.files.each do |file|
        p= link_to file.filename.to_s, url_for(file)

  -if user_signed_in?
    -if current_user.author_of?(question)
      = link_to 'Mark as best', mark_as_best_answer_path(answer), class: ('hidden' if answer.best?), method: :patch, remote: true

    = render('answers/controls', answer: answer)

    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}"}  do |f|
      p
        = f.label :body, 'Your answer'
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true
      p
        = f.submit 'Save'

app/views/answers/_controls.html.slim
- # parameters:
- #   answer - answer object

- if current_user&.author_of?(answer)
  .controls
    = link_to 'Edit', '#', class: "edit-answer-link", data: { "answer_id".to_sym => answer.id }
    |  |
    = link_to 'Delete', answer_path(answer), class: "destroy-answer", method: :delete, remote: true

app/views/answers/_new.html.slim
.new-answer-form
  .answer-errors
    = render 'shared/errors', resource: answer

  = form_with model: [question, answer], class: 'new-answer' do |f|
    p
      = f.label :body, 'Your answer'
      = f.text_area :body
    p
      = f.label :files
      = f.file_field :files, multiple: true

    = f.submit 'Add answer'

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.answers .answer#' + <%= j @answer.id %>).remove();

app/views/answers/mark_as_best.js.erb
var bestAnswerId = '<%= j @best_answer.id %>'

var prev_best_answer = $('.answer.best-answer');
prev_best_answer.removeClass('best-answer');
prev_best_answer.find('a:contains("Mark as best")').removeClass('hidden')

var new_best_answer = $('.answer#' + bestAnswerId);
new_best_answer.remove();
new_best_answer.addClass('best-answer');
new_best_answer.find('a:contains("Mark as best")').addClass('hidden')

$('.answers').prepend(new_best_answer);

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.errors.blank? %>
  var answerId = <%= j @answer.id %>;
  var answer = $('.answer#' + answerId);
  answer.html('<%= j(render 'answer', answer: @answer) %>');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'answers', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'questions', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="hmenu">
      <%= render 'devise/menu/registration_items' %>
      <%= render 'devise/menu/login_items' %>
    </ul>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/questions/_controls.html.slim
- # parameters:
- #   question - question object

- if current_user&.author_of?(question)
  .controls
    = link_to 'Edit', '#', class: "edit-question-link", data: { "question_id".to_sym => question.id }
    |  |
    = link_to 'Delete', question_path(question), class: "destroy-question", method: :delete, remote: true

app/views/questions/_question.html.slim
.question id= question.id
  = link_to question.title, question_path(question), class: 'title'

  - if user_signed_in?
    = render 'questions/controls', question: question

    .question-errors
      = render 'shared/errors', resource: question

    = form_with model: question, class: 'hidden', html: { id: "edit-question-#{question.id}"}  do |f|
      p
        = f.label :title, 'Title'
        = f.text_field :title
      p
        = f.label :body, 'Question'
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true

      = f.submit 'Save'

app/views/questions/destroy.js.erb
$('.questions .question#' + <%= j question.id %>).remove();

app/views/questions/index.html.slim
= link_to 'Ask question', new_question_path

h1 Questions:

.questions
  = render @questions

app/views/questions/mark_answer.js.erb
var bestAnswerId = '<%= j @best_answer.id %>'

var prev_best_answer = $('.answer.best-answer');
prev_best_answer.removeClass('best-answer');
prev_best_answer.find('a:contains("Mark as best")').removeClass('hidden')

var new_best_answer = $('.answer#' + bestAnswerId);
new_best_answer.remove();
new_best_answer.addClass('best-answer');
new_best_answer.find('a:contains("Mark as best")').addClass('hidden')

$('.answers').prepend(new_best_answer);

app/views/questions/new.html.slim
= render 'shared/errors', resource: question

= form_with model: question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true

  p= f.submit 'Ask'

app/views/questions/show.html.slim
h1.question-title= question.title
p.question-body= question.body

- if question.files.attached?
  - question.files.each do |file|
    p= link_to file.filename.to_s, url_for(file)

.answers
  = render @answers

= render('answers/new', question: question, answer: @answer) if user_signed_in?

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if question.files.attached? %>
  $('.notice').html('Files successfully added')
<% end %>

<% if @question.errors.blank? %>
  var questionId = <%= j @question.id %>;
  var question = $('.question#' + questionId);
  question.find('.edit-question-link').show();
  question.find('.title').html('<%= j @question.title %>');
  $('form#edit-question-' + questionId).addClass('hidden');
<% end %>

app/views/shared/_errors.html.slim
- # parameters: resource - question or answer

-if resource.errors.present?
  b "#{resource.errors.count} error(s) detected:"
  ul
    -resource.errors.full_messages.each do |message|
      li= message